### ISSUE TITLE
[BUG] 查询时出现：Read time out

### ISSUE THREAD

**Issue by ltfafei** [wgpsec/fofa_viewer#100]
fofa_viewer突然不能用了，前几天还用的好好的。测试了fofa apikey是会员，有效的。

![image](https://user-images.githubusercontent.com/43526141/176077155-0fd39fd4-542b-4fe8-8ef3-dccd40db1b2f.png)

![image](https://user-images.githubusercontent.com/43526141/176077269-33355ec7-50c7-4418-82c6-46fc8dc9a2ac.png)

**Comment by ltfafei** [comment]
使用fofa api是没有问题的：
![image](https://user-images.githubusercontent.com/43526141/176081472-7b4611b5-c34b-49c2-8ffa-32ba8b6dc673.png)

**Comment by f1ashine** [comment]
无法复现，我这在mac和windows是没问题的，SocketTimeout需要你看看是否设置了代理
<img width="786" alt="image" src="https://user-images.githubusercontent.com/26664765/176599955-82abbf6a-6d89-4b2e-946f-cdfdd44ec804.png">

**Comment by ltfafei** [comment]
没有设置代理，可能是网络原因

**Comment by Moe7ilin** [comment]
设置http代理后可以使用 再次禁用代理 也可以用了

**Comment by huan-cdm** [comment]
查询少量数据不显示超时，超多几千条就超时了

**Comment by yuyan-sec** [comment]
@f1ashine 1000条数字就超时，999就没超时。
![1](https://user-images.githubusercontent.com/43353917/177074951-cb02fd03-0b3b-4e76-b674-62eb2aa8d85e.png)
![2](https://user-images.githubusercontent.com/43353917/177074959-af8af69c-8901-4799-b619-8663a3b29c49.png)

**Comment by ZyRooting** [comment]
+1，只有把查询数量调整到100就可以查询成功，数据过大就会这样报错

**Comment by keac** [comment]
跟FOFA官方反馈了下，他们那边在排查，建议size不要调太大

**Comment by Ma1Dong** [comment]
确实，我也有这个bug

**Comment by f1ashine** [comment]
已修改超时时间为2分钟，可下载新版试用
