### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by zhizhuoshuma** [wgpsec/fofa_viewer#106]
**描述你遇到的问题**
在使用fofa_viewer 1.1.10版本中在选项中的重新加载会出现异常错误

**复现步骤**
![image](https://user-images.githubusercontent.com/64049774/182544791-59249b7d-ec12-48da-b8b5-cce568e45edc.png)

**预期行为**

重新加载出来数据

**屏幕截图**

![image](https://user-images.githubusercontent.com/64049774/182544812-cc447cdf-2d82-42eb-8323-55e5bb1551d6.png)

**运行环境**
 - 操作系统 
  Windows 10 
 - Java 版本 
java version "11.0.15.1" 2022-04-22 LTS
 - 软件版本 
1.1.10版本

**补充说明**

**Comment by f1ashine** [comment]
感谢师傅提出，问题已修复，其实也可以关闭tab 重新输入查询

**Comment by zhizhuoshuma** [comment]
> 感谢师傅提出，问题已修复，其实也可以关闭标签重新输入查询

是的但是这样操作有点复杂，还是这样刷新比较方便
