### ISSUE TITLE
[BUG] fofa语法中before不能和after连用

### ISSUE THREAD

**Issue by LeeDrizzle** [wgpsec/fofa_viewer#108]
**fofa语法中before不能和after连用**

在fofa官网中可以同时使用before和after来限定时间范围，而在工具中只能使用after或者bebore中的一个，当两个同时使用时，会出现语法错误提示

**复现步骤**

软件中befor和after两者都使用时：
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/50037452/187587627-ef8fb651-09b3-4f67-b084-6d471b2fa753.png">
官网上两者同时使用时：
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/50037452/187588009-9d0a9a87-c317-4785-8853-81e26a1005e1.png">
单独使用其中一个都不会出现问题
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/50037452/187588554-c33936d5-4b7b-455f-98a4-588478d9da10.png">

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/50037452/187588599-c9fea8d7-da6c-4759-84bc-76cb11c6bb60.png">

**运行环境**
 - 操作系统 
MacOS 12.5.1
   
 - Java 版本 
11.0.2-open
   
 - 软件版本 
Release 1.1.10
   

**补充说明**
无

**Comment by diauweb** [comment]
duplicate #95

**Comment by LeeDrizzle** [comment]
官网上是可以使用的，也就是说web查询可以连用，但是api不可以连用，是这样的吧
