### ISSUE TITLE
jdk11环境，查询提示报错[BUG] 

### ISSUE THREAD

**Issue by iPop** [wgpsec/fofa_viewer#109]
jdk11环境，fofa_viewer查询报错：
![image](https://user-images.githubusercontent.com/1647789/193412828-7a20c611-a303-47fe-ac69-a6cce9d44dca.png)
#

配置如下：
![image](https://user-images.githubusercontent.com/1647789/193412908-4ff51338-e868-45c8-aba6-e3674ace5455.png)

**Comment by keac** [comment]
@iPop 根据提示为f币不足，请检查自己的fofa账户

**Comment by iPop** [comment]
> @iPop 根据提示为f币不足，请检查自己的fofa账户

thx so much
