### ISSUE TITLE
运行报错820006

### ISSUE THREAD

**Issue by Sz0th** [wgpsec/fofa_viewer#11]
win10家庭版 java1.8 最新版release
配置完config文件后，点击查询直接报错，未产生error.log文件

![图片](https://user-images.githubusercontent.com/81865289/117528614-a127d780-b005-11eb-89c9-da280360f741.png)
若需提供其他信息，烦请回复

**Comment by f1ashine** [comment]
如果错误不太清楚，可以在cmd下运行`java -jar fofa_viewer.jar`，如果有报错会直接显示在命令行界面，可以试试

**Comment by Sz0th** [comment]
感谢回复，使用java -jar fofa_viewer.jar后可以成功运行，虽然仍会报错
![图片](https://user-images.githubusercontent.com/81865289/118207629-a7033a00-b497-11eb-9c57-6343b3250c49.png)
后结束命令，双击运行也可成功使用
