### ISSUE TITLE
[BUG] JDK11环境导出失败

### ISSUE THREAD

**Issue by iPop** [wgpsec/fofa_viewer#110]
![图片](https://user-images.githubusercontent.com/1647789/194683749-3f25874e-66eb-400f-8ab8-29cf56863a95.png)

![图片](https://user-images.githubusercontent.com/1647789/194683766-33171e77-af89-489c-9536-6500a7bac354.png)

**Comment by keac** [comment]
请使用 java -jar 运行查看是否有报错，并且贴上方便我们定位问题

**Comment by iPop** [comment]
![图片](https://user-images.githubusercontent.com/1647789/194684718-1a8985f2-1dab-4b0f-8c2e-19a880171098.png)

**Comment by iPop** [comment]
可以正常启动，没报错。

**Comment by iPop** [comment]
> 请使用 java -jar 运行查看是否有报错，并且贴上方便我们定位问题

![图片](https://user-images.githubusercontent.com/1647789/194684751-a2086ceb-9af6-4702-8a6b-041aba6080a6.png)

可以正常启动，没报错。

**Comment by diauweb** [comment]
请提供出现导出失败时的控制台截图。

**Comment by iPop** [comment]
> 请提供出现导出失败时的控制台截图。

![图片](https://user-images.githubusercontent.com/1647789/194684857-54888ffe-708e-4b95-b94c-f71bf163759c.png)
导出失败如图

**Comment by diauweb** [comment]
请提供出现导出失败时的**控制台**截图。

**Comment by bambooqj** [comment]
2022-10-16 01:52:14.516 ERROR DataUtil.java.java:75-exportToExcel:
com.alibaba.excel.exception.ExcelGenerateException: java.lang.ExceptionInInitializerError
        at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl.java:64)
        at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:161)
        at com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:146)

**Comment by SevenC-base** [comment]
java --add-opens java.base/java.lang=ALL-UNNAMED -jar fofaviewer.jar

**Comment by SevenC-base** [comment]
> 2022-10-16 01:52:14.516 错误 DataUtil.java.java:75-exportToExcel: com.alibaba.excel.exception.ExcelGenerateException: java.lang.ExceptionInInitializerError at com.alibaba.excel.write.ExcelBuilderImpl.addContent(ExcelBuilderImpl .java:64) 在 com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:161) 在 com.alibaba.excel.ExcelWriter.write(ExcelWriter.java:146)

java --add-opens java.base/java.lang=ALL-UNNAMED -jar fofaviewer.jar

**Comment by f1ashine** [comment]
实测通过`java -jar 启动`是可以正常导出的，如果不能则可能跟jdk有关系，我在将jdk打包成MacOS使用的App时也出现了像你这样的报错，但是你这个异常信息不完整。
<img width="872" alt="image" src="https://user-images.githubusercontent.com/26664765/197327918-9a4a47a2-7f68-48e4-a12a-426f199fd6da.png">
我通过重新配置jre使用jre11 可以正常导出。
