### ISSUE TITLE
默认显示一年数据量的问题

### ISSUE THREAD

**Issue by Ma1Dong** [wgpsec/fofa_viewer#111]
师傅好，这个工具好像只显示一年的数据量是吗，fofaapi好像是有个full=true参数可以选择所有的数据量而不是一年的，这个工具在哪查看所有的呢
![image](https://user-images.githubusercontent.com/52943794/195517152-5cddbf47-7ae6-4de4-8485-ccdcb210b3e0.png)

**Comment by f1ashine** [comment]
<img width="590" alt="image" src="https://user-images.githubusercontent.com/26664765/196323070-9616f0c4-4476-47f3-b6de-5ec404060ff2.png">
勾选这个即可

**Comment by Ma1Dong** [comment]
好的，谢谢师傅
