### ISSUE TITLE
状态码400

### ISSUE THREAD

**Issue by toor123Himmel66** [wgpsec/fofa_viewer#114]
win10 jdk1.8   
配置好api
v1.1.11

![image](https://user-images.githubusercontent.com/100980418/197316258-65cb6a3e-6364-47f3-b57a-283dba9f7f98.png)

sorry  啊

**Comment by keac** [comment]
看起来语句使用了中文标点符号`”` 请参考语法手册

**Comment by toor123Himmel66** [comment]
师傅 微信搞一下
