### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by Explore-c** [wgpsec/fofa_viewer#12]
当host列结果不是http://这样开头的就没法直接跳转到浏览器
希望可以增加一个记住搜索语法的功能

**Comment by f1ashine** [comment]
搜索历史可以加，不是http开头的不打开浏览器是我最开始设置的规则，后面更新会改下😅

**Comment by Explore-c** [comment]
> 搜索历史可以加，不是http开头的不打开浏览器是我最开始设置的规则，后面更新会改下😅

今天发现了个bug，查询语法：ip_country="CN"，没有输出结果，fofa上是有的
![image](https://user-images.githubusercontent.com/46821530/118491573-b7ded480-b751-11eb-9881-c8b6a797a643.png)

**Comment by f1ashine** [comment]
版本已更新，师傅可以再试试
