### ISSUE TITLE
重新加载功能有bug

### ISSUE THREAD

**Issue by ryuuz4k1** [wgpsec/fofa_viewer#120]
**描述你遇到的问题**
点击重新加载，中文会变成乱码

**屏幕截图**
![image](https://user-images.githubusercontent.com/99396168/206651229-5b72bef3-59c8-45f5-9246-89b0cc800776.png)

**Comment by f1ashine** [comment]
应该是字符串编码的原因，mac系统和windows系统的默认编码不一样，在mac下使用无影响，在windows 下使用就会造成乱码，后续我加个指定编码应该就好了，感谢 :)
