### ISSUE TITLE
计算favicon hash功能有bug

### ISSUE THREAD

**Issue by ryuuz4k1** [wgpsec/fofa_viewer#121]
**描述你遇到的问题**
计算favicon hash功能计算出来的哈希值不正确，比如tomcat的图标哈希值为“-297069493”，计算出来却是“3726739...”
**屏幕截图**
![image](https://user-images.githubusercontent.com/99396168/206652128-655a0c2e-505f-4f1b-a538-d8142170af15.png)

**Comment by f1ashine** [comment]
请提供一下你提到的tomcat的图标文件

**Comment by ryuuz4k1** [comment]
icon_hash="-297069493" 在工具里搜这个图标，搜索结果里随便选个url复制一下，粘贴到计算favicon hash里，计算出来的哈希值和之前的不一样。













在 2022-12-10 00:03:29，"f1ashine" ***@***.***> 写道：

请提供一下你提到的tomcat的图标文件

**Comment by f1ashine** [comment]
计算favicon hash这个框是需要携带favicon链接的，不是说你直接在搜索结果里复制url就能自动计算favicon hash的，如果还是看不懂的话建议你使用右键里的这个按钮
![image](https://user-images.githubusercontent.com/26664765/209679595-d96cb5e9-4e7a-418b-830e-2869ec6953d5.png)

**Comment by ryuuz4k1** [comment]
明白了，感谢！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年12月27日 22:20 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [wgpsec/fofa_viewer] 计算favicon hash功能有bug (Issue #121) |

计算favicon hash这个框是需要携带favicon链接的，不是说你直接在搜索结果里复制url就能自动计算favicon hash的，如果还是看不懂的话建议你使用右键里的这个按钮
