### ISSUE TITLE
时间范围查询语法错误

### ISSUE THREAD

**Issue by 1rm** [wgpsec/fofa_viewer#125]
![屏幕截图 2023-02-02 092032](https://user-images.githubusercontent.com/28972049/216207834-afe6de24-48f4-47fe-a705-93da8fcc309c.png)

**Comment by f1ashine** [comment]
fofa api语法设置问题，跟工具本身无关

**Comment by ppuuoo** [comment]
如何解决此问题呢

**Comment by thebatmanfuture** [comment]
https://github.com/thebatmanfuture/fofa_search
