### ISSUE TITLE
[BUG] 导出数据崩溃

### ISSUE THREAD

**Issue by brucelsone** [wgpsec/fofa_viewer#128]
**描述你遇到的问题**

尝试进行数据导出直接程序崩溃。

**复现步骤**

**预期行为**

**屏幕截图**

<img width="1511" alt="image" src="https://user-images.githubusercontent.com/101378596/228099715-0f8b68fa-89af-47ca-9cda-c8c8c095cc11.png">

**运行环境**
 - 操作系统 
   
macos monterey（m1芯片）
 - Java 版本 
   
java version "1.8.0_191"
 - 软件版本 
   
1.1.12_JDK8

**Comment by keac** [comment]
请升级下jdk版本到jdk1.8的最新版
