### ISSUE TITLE
macbook[BUG] 

### ISSUE THREAD

**Issue by BypassKing** [wgpsec/fofa_viewer#129]
查询条件输入后，点击查询 报这个错误。 
已配置好email key
错误信息: javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake
Java 环境
java version "1.8.0_271"
Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)

系统
MacBook pro
MacOS 13.1

**Comment by keac** [comment]
@BypassKing 看着是网络问题，检查下网络情况？

**Comment by BypassKing** [comment]
eeeee.我网络没有任何毛病。一直都是这个情况。

报错 是什么证书问题。。。

**Comment by BypassKing** [comment]
我在 config.properties 文件中 增加了 email key 保存后 

在运行，就会提示我 配置错误，是否打开配置面板进行配置

**Comment by keac** [comment]
@BypassKing 检查是否开了代理软件，如果配置错误可以删掉配置文件重新打开软件配置

**Comment by f1ashine** [comment]
mac 新系统由于新增了完全磁盘访问权限配置，当用户双击打开jar时将无法访问配置文件，需要自行配置（如下图所示），JavaLauncher.app 路径位于 /System/Library/CoreServices/JavaLauncher.app
<img width="494" alt="image" src="https://user-images.githubusercontent.com/26664765/229270235-5ead2d58-5fb5-4e29-97b4-695d5b5ac22a.png">


> 我在 config.properties 文件中 增加了 email key 保存后
> 
> 在运行，就会提示我 配置错误，是否打开配置面板进行配置
