### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by SEK1R0zh** [wgpsec/fofa_viewer#130]
![image](https://user-images.githubusercontent.com/95747770/231678870-6a37b78a-88b0-454a-85a3-ece6eea5c1a3.png)
我是高级会员但是无法勾选fid进行查询

**Comment by keac** [comment]
根据fofa官方api说明，使用fid需要升级为企业为会员
详见：https://fofa.info/api
![image](https://user-images.githubusercontent.com/16091665/231679751-93c1dc7f-78de-43cd-848e-004abe7d020b.png)
