### ISSUE TITLE
打开不了[BUG] 

### ISSUE THREAD

**Issue by Hxshell** [wgpsec/fofa_viewer#131]
![image](https://user-images.githubusercontent.com/114931663/235361885-5ffe1ead-0eaf-4487-926f-8d5c61c59a1d.png)
 
打开不了软件
![image](https://user-images.githubusercontent.com/114931663/235361921-cd7276c7-9f82-43e1-a0bd-a66bb487fe27.png)
显示这个

**Comment by f1ashine** [comment]
你用jdk11打开了用jdk8编译的版本，换另一个就行了
