### ISSUE TITLE
[FEAT] 一种导出全部数据的思路

### ISSUE THREAD

**Issue by SnowMeteors** [wgpsec/fofa_viewer#133]
**我遇到了什么问题让我希望添加这项功能**
我希望能导出全部数据

**你希望的解决方案**
如app="solr"查询出来的总数据为2w条，可以使用before关键字获取到1w条左右并导出
第一次before="2023-01-05"查询出来的数据为10256条，那么就导出这一页。
第二次before="2023-03-1"查询出来的数据为10256+10000条，那么就导出这一页。
最后将这两万条数据合并，并去重，就能全部导出数据。
我目前人工就是这样导出的，希望工具能加入此功能。

**Comment by SnowMeteors** [comment]
https://zhuanlan.zhihu.com/p/641456302

fofa 官方已有api

**Comment by thebatmanfuture** [comment]
我已经二开完了，你们继续用fofa_viewer吧
![image](https://github.com/wgpsec/fofa_viewer/assets/75312962/32f830b0-3f7f-4d26-825a-bf09bdda5322)

**Comment by keac** [comment]
欢迎提交PR~

**Comment by thebatmanfuture** [comment]
https://github.com/thebatmanfuture/fofa_search
