### ISSUE TITLE
[BUG] Win11下 JDK17 运行时界面乱码

### ISSUE THREAD

**Issue by xsshk** [wgpsec/fofa_viewer#134]
**描述你遇到的问题**

出现界面乱码

**复现步骤**

Windows11 + JDK17 出现界面乱码
**预期行为**

**屏幕截图**

![image](https://github.com/wgpsec/fofa_viewer/assets/71780423/90d32669-929c-444e-94bc-13b879cd4a99)
**运行环境**
 - 操作系统 
   
![image](https://github.com/wgpsec/fofa_viewer/assets/71780423/f49080c7-b70b-4243-b61c-d43dba4cbe28)

 - Java 版本 
   
java version "17.0.6" 2023-01-17 LTS
Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.6+9-LTS-190, mixed mode, sharing)
 - 软件版本 
   
V1.1.12

**补充说明**

尝试过英文版，依旧乱码
1.1.12以及之前版本均乱码

**Comment by keac** [comment]
请尝试使用JDK11版本，JDK17目前兼容性未知
