### ISSUE TITLE
[BUG] 用不了

### ISSUE THREAD

**Issue by Hxshell** [wgpsec/fofa_viewer#140]
老是提示我说f点不足
![image](https://github.com/wgpsec/fofa_viewer/assets/114931663/7e534a79-045c-42aa-985a-a8016c48cefa)
java是1.8.0_361版本
win11

**Comment by keac** [comment]
@Hxshell 请查看官方文档，调用的为API接口

**Comment by Hxshell** [comment]
师傅，我是官方的api呀，不是这两个吗
![20230912115655](https://github.com/wgpsec/fofa_viewer/assets/114931663/cb8f0564-9df8-4175-8b82-1c60ebb87a9d)

**Comment by Hxshell** [comment]
> 

师傅，我的问题，解决了，谢谢
