### ISSUE TITLE
导出execl出错

### ISSUE THREAD

**Issue by henwuyoukeai** [wgpsec/fofa_viewer#145]
java 版本
![image](https://github.com/wgpsec/fofa_viewer/assets/128207611/9d5c1983-e606-46b6-8a6d-b0c893a3a612)

报错信息
![image](https://github.com/wgpsec/fofa_viewer/assets/128207611/e2576393-926b-4879-873e-25e3e7a54e61)

**Comment by sun2pwn** [comment]
同样问题，求解决

**Comment by keac** [comment]
请仔细阅读README
https://github.com/wgpsec/fofa_viewer?tab=readme-ov-file#%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E
