### ISSUE TITLE
[BUG] Java8及Java17.0.9版本下显示导出失败

### ISSUE THREAD

**Issue by twoning** [wgpsec/fofa_viewer#146]
**描述你遇到的问题**

导出查询数据报错， Java8及Java17.0.9版本下显示导出失败
**复现步骤**

通过Java17运行fofaviewer，可正常查询数据，but无法正常导出，提示导出失败，会在目标路径生成Excel文件，但是为空。
**预期行为**

**屏幕截图**

**运行环境**
 - 操作系统 
   
Microsoft Windows 11 专业版
 - Java 版本 
   
java version "17.0.9" 2023-10-17 LTS
Java(TM) SE Runtime Environment (build 17.0.9+11-LTS-201)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.9+11-LTS-201, mixed mode, sharing)
 - 软件版本 
   
Fofaviewerv1.1.13
**补充说明**

**Comment by keac** [comment]
请查看阅读仓库readme

**Comment by twoning** [comment]
Thank you. Problem solved
