### ISSUE TITLE
[BUG] jdk1.8打不开,需要命令行执行jar包

### ISSUE THREAD

**Issue by Throughmountain** [wgpsec/fofa_viewer#148]
**描述你遇到的问题**

**复现步骤**

**预期行为**

**屏幕截图**

**运行环境**
 - 操作系统 
   
 - Java 版本 
   
 - 软件版本 
   

**补充说明**

**Comment by keac** [comment]
非工具问题，自行配置的环境 参考以下文章或者搜索引擎添加注册表尝试解决
https://edu.yijinglab.com/question/4532
https://blog.csdn.net/lyhDream/article/details/17148797

**Comment by Throughmountain** [comment]
谢谢兄弟，问题解决了
