### ISSUE TITLE
after和before不能同时使用

### ISSUE THREAD

**Issue by hunzi0** [wgpsec/fofa_viewer#149]
![20240319111527](https://github.com/wgpsec/fofa_viewer/assets/57057346/aa0b992d-5e68-4d4c-9b41-d3645097a9a0)
![20240319111545](https://github.com/wgpsec/fofa_viewer/assets/57057346/5840ac93-cd70-4432-97d7-ac11e549a8f9)

**Comment by keac** [comment]
@hunzi0 请看fofa官方API手册限制
