### ISSUE TITLE
查询数量和导出数量不一致

### ISSUE THREAD

**Issue by badboycxcc** [wgpsec/fofa_viewer#15]
"jboss" && region="HK" &&  after="2021-01-01" 查询得到100条，导出后只有7条url？

**Comment by f1ashine** [comment]
这个主要是我之前观察到就是fofa它本身会去爬资产嘛，然后返回爬到的端口数据就会有两条一样的（一个有http，一个没有），就比如这种（这个可能是蜜罐）
![image](https://user-images.githubusercontent.com/26664765/119613738-02d2a900-be30-11eb-9958-5727c1d29a85.png)
然后一般来说这种某个端口只有一条标记为http或者https的数据，有比较大的几率打不开，所以我就只是让它显示在上边，没有做导出，避免在扫描导出数据的时候时间浪费在打不开的站点上，当然其中也有部分的数据可能是打得开的

**Comment by badboycxcc** [comment]
原来如此，懂了。
