### ISSUE TITLE
[BUG] 弹窗报错请求错误302

### ISSUE THREAD

**Issue by pule150** [wgpsec/fofa_viewer#152]
<img width="752" alt="PixPin_2024-05-29_10-58-00" src="https://github.com/wgpsec/fofa_viewer/assets/88131982/eb20b4b3-5f5a-4b80-ad7f-4a6ecae233a3">
<img width="752" alt="PixPin_2024-05-29_10-58-00" src="https://github.com/wgpsec/fofa_viewer/assets/88131982/4bb68be9-2cb2-4322-9b33-2781c8ac5cc0">

**Comment by f1ashine** [comment]
请使用新版本
