### ISSUE TITLE
[BUG] 最新版jd8报错403权限不足

### ISSUE THREAD

**Issue by DouLiYouTang31** [wgpsec/fofa_viewer#153]
**描述你遇到的问题**

**复现步骤**

**预期行为**

**屏幕截图**

**运行环境**
 - 操作系统 
   
 - Java 版本 
   
 - 软件版本 
   

**补充说明**

**Comment by DouLiYouTang31** [comment]
使用1.1.13正常，1.1.14未测试

**Comment by f1ashine** [comment]
师傅贴个截图

**Comment by DouLiYouTang31** [comment]
![image](https://github.com/wgpsec/fofa_viewer/assets/99908721/09473d63-fa8c-4325-823e-80248bd0cb8d)
教育会员账号

**Comment by AdminZch0** [comment]
有解决了吗，研发大大 @f1ashine

**Comment by f1ashine** [comment]
你更换网络之后能用吗，目前默认启动查询的所有字段都是基于官网的[api文档](https://fofa.info/api)里的无权限要求去调用的，我也和fofa的官方人员沟通过了，如果返回这个状态码应该是账号或者网络问题，

**Comment by DouLiYouTang31** [comment]
> 你更换网络之后能用吗，目前默认启动查询的所有字段都是基于官网的[api文档](https://fofa.info/api)里的无权限要求去调用的，我也和fofa的官方人员沟通过了，如果返回这个状态码应该是账号或者网络问题，

刚刚测试了一下，14版本就报403，13版本正常，使用的是同一个账号同一个key
![屏幕截图 2024-06-24 104600](https://github.com/wgpsec/fofa_viewer/assets/99908721/5286013f-2ae5-4115-98ac-2a7e1679328e)

**Comment by AdminZch0** [comment]
> > 你更换网络之后能用吗，目前默认启动查询的所有字段都是基于官网的[api文档](https://fofa.info/api)里的无权限要求去调用的，我也和fofa的官方人员沟通过了，如果返回这个状态码应该是账号或者网络问题，
> 
> 刚刚测试了一下，14版本就报403，13版本正常，使用的是同一个账号同一个key ![屏幕截图 2024-06-24 104600](https://private-user-images.githubusercontent.com/99908721/342185930-5286013f-2ae5-4115-98ac-2a7e1679328e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxOTg5NzMsIm5iZiI6MTcxOTE5ODY3MywicGF0aCI6Ii85OTkwODcyMS8zNDIxODU5MzAtNTI4NjAxM2YtMmFlNS00MTE1LTk4YWMtMmE3ZTE2NzkzMjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDAzMTExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMzFjYTYwOGQzYTAyYjBmYWU1NDFhMzU5NzBjY2IzNDE5NDIwMzg1ZTViNjM0MDFiNjU5ODM0ZjFmNTUzYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yCko1LKOFYe5EcI4yR5DK3fCnSSYHY6PvkTXn7KdMZI)

+1，我之前一直用1.1.8，因为心血来潮想试试最新版，发现1.1.14和1.1.15都有问题

**Comment by f1ashine** [comment]
> > > 你更换网络之后能用吗，目前默认启动查询的所有字段都是基于官网的[api文档](https://fofa.info/api)里的无权限要求去调用的，我也和fofa的官方人员沟通过了，如果返回这个状态码应该是账号或者网络问题，
> > 
> > 
> > 刚刚测试了一下，14版本就报403，13版本正常，使用的是同一个账号同一个key ![屏幕截图 2024-06-24 104600](https://private-user-images.githubusercontent.com/99908721/342185930-5286013f-2ae5-4115-98ac-2a7e1679328e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxOTg5NzMsIm5iZiI6MTcxOTE5ODY3MywicGF0aCI6Ii85OTkwODcyMS8zNDIxODU5MzAtNTI4NjAxM2YtMmFlNS00MTE1LTk4YWMtMmE3ZTE2NzkzMjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI0VDAzMTExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMzFjYTYwOGQzYTAyYjBmYWU1NDFhMzU5NzBjY2IzNDE5NDIwMzg1ZTViNjM0MDFiNjU5ODM0ZjFmNTUzYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yCko1LKOFYe5EcI4yR5DK3fCnSSYHY6PvkTXn7KdMZI)
> 
> +1，我之前一直用1.1.8，因为心血来潮想试试最新版，发现1.1.14和1.1.15都有问题 是不是因为我买的是最之前的300的会员，查不了有些字段

实际是教育会员的问题，已联系fofa官方解决，你也是教育会员吗

**Comment by DouLiYouTang31** [comment]
官方接口问题，已解决
