### ISSUE TITLE
输入查询时候，没输入完就卡

### ISSUE THREAD

**Issue by lazydogdog** [wgpsec/fofa_viewer#17]
输入查询的时候每打一段语句就卡一下，比如title=”xx“ ,title才打了三个字母就卡一下

**Comment by f1ashine** [comment]
那是因为有智能查询那个下拉框这个功能，我设置了延时1.5s自动查询在下拉框显示结果，由于java ui的原因，如果网络请求比较卡的话会导致这个问题，后续我会限制请求的响应时间，尽量保证输入的时候不卡
