### ISSUE TITLE
报错和小建议

### ISSUE THREAD

**Issue by G-MAN-TOP1** [wgpsec/fofa_viewer#18]
搜索server=“weblogic”、server=“tomcat“中间件后会卡顿后报错，搜索其他像“Apache”、“Nginx”数据量更大的反而没有问题。
报错内容：
Premature end of chunk coded message    
body：closing chunk expected
小建议：
导出的数据能更详细一点，能分开列出title、ip等

**Comment by f1ashine** [comment]
无法复现，我这边都查出来了，提bug麻烦截个图，然后这个建议看不懂。。
![image](https://user-images.githubusercontent.com/26664765/120897120-35ae4580-c657-11eb-8565-15f3bbf3c63e.png)

**Comment by G-MAN-TOP1** [comment]
好的，把”排除干扰“勾上确实就可以了。
这是不加上的报错截图：

![图片](https://user-images.githubusercontent.com/71801814/120951940-95ead780-c77c-11eb-9eb9-eaa148f63a02.png)
建议的意思是导出当前页面的数据能更丰富一点，像TItle、IP之类的能一起导出，因为目前我看到的导出数据只有HOST数据

**Comment by f1ashine** [comment]
测试发现如果配置文件里的maxSize设置为10000条的时候查询server="weblogic"可能会出现这个错误，疑似是这个蜜罐的server头的问题，建议把maxSize设置小一点再请求，然后excel也更新了
