### ISSUE TITLE
不知道师傅有没有考虑过加个分页功能

### ISSUE THREAD

**Issue by Gitqiubai** [wgpsec/fofa_viewer#20]
这是我用过最舒服的采集器了，可以直接右键搜索C段搜子域名，但有时候搜索出一次性加载的结果有几百行有点多，不晓得师傅有没有考虑过分页的问题

**Comment by f1ashine** [comment]
现在已经可以分页加载了啊，只要你滚轮滑到最下面就会自动加载，如果你觉得一次加载的比较多，你可以修改下maxSize这个参数，只是没显示加载了多少页，这个我考虑下次更新时加上。
