### ISSUE TITLE
mac使用报错

### ISSUE THREAD

**Issue by sp4rkw** [wgpsec/fofa_viewer#23]
MacBook-Pro fofaviewer_1.0.7_ % java -version    
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (Zulu 8.54.0.21-CA-macos-aarch64) (build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (Zulu 8.54.0.21-CA-macos-aarch64) (build 25.292-b10, mixed mode)
MacBook-Pro fofaviewer_1.0.7_ % java -noverify -Xdock:icon=fofa_viewer.icns -jar fofaviewer.jar
错误: 找不到或无法加载主类 org.fofaviewer.main.MainApp

**Comment by f1ashine** [comment]
建议试用oracle jdk1.8的版本

**Comment by stemmm** [comment]
从javafx网站下载相关版本的javafx依赖下来，运行的时候直接从相关目录导入再运行fofaviewer.jar即可。
> https://gluonhq.com/products/javafx/
<img width="1728" alt="image" src="https://github.com/wgpsec/fofa_viewer/assets/53185620/0716ebb2-4d32-44a8-9384-3ca8b0b5c61b">
`java --module-path /Library/Java/Extensions/javafx-sdk-17.0.9/lib/ --add-modules=javafx.base,javafx.controls,javafx.fxml,javafx.graphics,javafx.media,javafx.swing,javafx.web -jar fofaviewer.jar`
