### ISSUE TITLE
Request params not valid

### ISSUE THREAD

**Issue by zzlyzq** [wgpsec/fofa_viewer#25]
![image](https://user-images.githubusercontent.com/1989900/128624201-d99a99c6-7364-47e3-8f29-74348543fb4c.png)

使用方法：下载软件，并修改配置文件，加入账号、key信息；输入ip="1.1.1.1"，点击查询后，出现报错。
报错内容：Request params not valid

**Comment by f1ashine** [comment]
![image](https://user-images.githubusercontent.com/26664765/128654938-9de4f4b1-630a-44cc-be1c-5f51acffb796.png)
这个返回值是fofa设定的，报错的话肯定就是你哪输错了，我这没问题
