### ISSUE TITLE
请问普通会员可以用吗

### ISSUE THREAD

**Issue by hakuQAQ** [wgpsec/fofa_viewer#28]
设置了config.properties，只是简单的查询，语句：domain="qq.com" ，没有勾选排除干扰。提示用户不是高级会员。
![%~Y9V8EAMM40EGT }{~$0C2](https://user-images.githubusercontent.com/52093689/131297929-e7535701-370d-4d8e-9800-a167ea04d981.png)

**Comment by f1ashine** [comment]
工具仅面向会员用户使用哦

**Comment by hakuQAQ** [comment]
> 工具仅面向会员用户使用哦

普通会员也是会员叭，也可以用fofa api的。。。

**Comment by f1ashine** [comment]
修改conifg.properties中的maxSize为100应该就可以了，普通会员上限只有100条。
