### ISSUE TITLE
fafa view 在win10下报错

### ISSUE THREAD

**Issue by Eloco** [wgpsec/fofa_viewer#33]
你好，遇到了如下问题，是需要降低java版本吗

$ java -jar fofaviewer.jar
����: �Ҳ������޷��������� org.fofaviewer.main.MainApp
ԭ��: java.lang.NoClassDefFoundError: javafx/application/Application

$ java -version
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-46)
OpenJDK 64-Bit Server VM (build 14.0.2+12-46, mixed mode, sharing)

**Comment by keac** [comment]
最新版本已修复，下载JDK11版本的直接可以运行
