### ISSUE TITLE
client 401

### ISSUE THREAD

**Issue by yandatou** [wgpsec/fofa_viewer#36]
我用自己的email+key 可以登录 fofa cli，但是使用fofa_viewer的包，提示401未授权。求助。

<img width="464" alt="Screen Shot 2021-10-18 at 11 46 16" src="https://user-images.githubusercontent.com/21006814/137666468-4104ded9-24b1-40d9-8159-8bdfef45c3cb.png">

**Comment by keac** [comment]
你好，可以提供下fofa的email吗，我们跟fofa官方沟通下
