### ISSUE TITLE
在mac中很方便的启动fofa_viewer

### ISSUE THREAD

**Issue by zhaodie** [wgpsec/fofa_viewer#4]
因为昨天晚上在mac中一直无法启动fofa_viewer,然后今天想到了一种解决方法，附上文章地址
http://www.jizhao.net.cn/index.php/2021/04/15/mac%e8%a7%a3%e5%86%b3fofa_viewer%e6%97%a0%e6%b3%95%e5%90%af%e5%8a%a8/

**Comment by keac** [comment]
感谢师傅，已经将文章添加至Readme
