### ISSUE TITLE
导出失败

### ISSUE THREAD

**Issue by soapffz** [wgpsec/fofa_viewer#49]
用的是最新版本的 但是导出失败

选的是文件夹，之前的版本导出没问题 

![image](https://user-images.githubusercontent.com/43143519/139537445-8cbfe59d-b7fa-47d3-a17d-8ea3cead52cd.png)

**Comment by hyp20010106** [comment]
我也是出现了这个问题

**Comment by keac** [comment]
请问是在什么系统环境、java版本下报错的

**Comment by soapffz** [comment]
win10 jdk 16.0.2
![image](https://user-images.githubusercontent.com/43143519/140061271-e34d7b64-eab9-4f3c-b52b-6d8ffaa3c98c.png)

**Comment by keac** [comment]
参考ISSUE #50
