### ISSUE TITLE
jdk11提示确实配置文件

### ISSUE THREAD

**Issue by changfeng-zhang** [wgpsec/fofa_viewer#51]
![image](https://user-images.githubusercontent.com/85071313/140452331-0add2f3e-8b66-49be-9916-8932a96e5966.png)

**Comment by changfeng-zhang** [comment]
缺少配置文件。但是配置文件存在呀

**Comment by keac** [comment]
请把你的系统环境、JDK版本 以及你怎么打开的方式描述下 我们排查下

**Comment by changfeng-zhang** [comment]
![image](https://user-images.githubusercontent.com/85071313/140462668-e7e4a02e-7182-4bf0-aedd-594f42e779ce.png)
![image](https://user-images.githubusercontent.com/85071313/140462733-3cf45f97-f30d-4a90-8d33-ad8eefdbe581.png)
![image](https://user-images.githubusercontent.com/85071313/140462843-b55adc0f-a3f5-448d-a66f-b0a4162d8dc4.png)
jdk11 macos11 命令行打开不报错 就正常使用java环境双击打开报错

**Comment by f1ashine** [comment]
![image](https://user-images.githubusercontent.com/26664765/140464072-afeef55e-eeab-46a8-9b69-68455f7fd7bc.png)
我这正常运行

**Comment by f1ashine** [comment]
可以参考这个https://www.jianshu.com/p/e2a881aa047e

**Comment by changfeng-zhang** [comment]
好的感谢
