### ISSUE TITLE
关于m1运行报错

### ISSUE THREAD

**Issue by winkdoge** [wgpsec/fofa_viewer#54]
本人环境为：
jdk8，jdk11，jdk17
本地三个版本编译java文件运行均正常，但是jar fofaviewer.jar 却报找不到主类错误

**Comment by f1ashine** [comment]
找朋友问了下，他的m1用jdk8跑是没问题，可能是你的jdk问题，试试用arm的jdk运行，另外如果安装了burp可以正常运行的话，可以尝试用burp自带的jdk运行，如：
```
/Applications/Burp Suite Professional.app/Contents/PlugIns/jre.bundle/Contents/Home/bin/java -jar fofaviewer.jar
```

**Comment by diauweb** [comment]
@winkdoge 请提供启动时使用的具体命令和输出信息

**Comment by winkdoge** [comment]
@diauweb 
已经解决了
过程如下：
先卸掉已经安装的jdk，我这里安装了zulu的jdk
再安装oracle官网jdk8即可
链接如下
https://www.oracle.com/java/technologies/downloads/#java8
