### ISSUE TITLE
404 not found问题

### ISSUE THREAD

**Issue by qahehe** [wgpsec/fofa_viewer#58]
已经填好了fofa信息，是高级会员
<img width="640" alt="Snipaste_2021-12-10_11-41-22" src="https://user-images.githubusercontent.com/25258443/145513573-3cc3334c-9380-4a92-9d95-1c790c972cca.png">
<img width="500" alt="Snipaste_2021-12-10_11-41-33" src="https://user-images.githubusercontent.com/25258443/145513582-2f46a272-c8bb-494c-8438-18ae3181706c.png">

**Comment by keac** [comment]
@qahehe FOFA 官方 10：46 发布公告
群公告
尊敬的FOFA用户，您好！

为提供更好的服务，FOFA将进行系统升级维护，预计升级时间2小时。届时网站和API可能无法正常打开和使用。因此给您带来的不便我们深表歉意！

FOFA团队
