### ISSUE TITLE
820000报错，之前都好好的 突然这样 有师傅遇到过吗？》

### ISSUE THREAD

**Issue by chain00x** [wgpsec/fofa_viewer#61]

**Comment by keac** [comment]
@chain00x 请提供下详细截图，以及是怎么触发这个bug的

**Comment by f1ashine** [comment]
举个例子：查询语句不符合语法规定，带入了中文引号就会触发这个错误，我这里是最后带上了中文双引号报错。
![image](https://user-images.githubusercontent.com/26664765/147850592-3c0ff42b-dcf3-4a85-934a-5cc9fcff0a73.png)
