### ISSUE TITLE
[BUG] mac

### ISSUE THREAD

**Issue by tin7safe** [wgpsec/fofa_viewer#64]
**描述你遇到的问题**
双击运行导致 配置文件路径错误。
如果用java -jar fofa.jar就没问题。

**复现步骤**
双击运行

**屏幕截图**
![image](https://user-images.githubusercontent.com/22520854/147952171-200e9bd8-e3b6-4956-9d6e-45f52481ee3a.png)

**运行环境**
 - 操作系统 :macOS Monterey
 - Java 版本:Java(TM) SE Runtime Environment (build 1.8.0_301-b09)
 - 软件版本: 1.1.4

**Comment by tin7safe** [comment]
我感觉自己像找茬的。哈哈
https://github.com/wgpsec/fofa_viewer/blob/master/docs/mac.md

**Comment by keac** [comment]
问题已解决
