### ISSUE TITLE
[BUG] update fofo.so from fofa.info

### ISSUE THREAD

**Issue by signfind** [wgpsec/fofa_viewer#67]
**描述你遇到的问题**
清晰、准确地描述你遇到了什么问题。

**复现步骤**
出现问题前进行的操作：
1. 使用...功能
2. 输入了...
3. 出现了...问题

**预期行为**
描述你预期的正确行为

**屏幕截图**
最好提供出现问题时的截图。

**运行环境**
 - 操作系统 (例. Windows 10 21H1)
 - Java 版本 (`java -version`) (例. `java version "17.0.1" 2021-10-19 LTS`)
 - 软件版本 (例. 1.1.4_JDK8)

**补充说明**
其他相关内容，如配置文件和Stacktrace

**Comment by signfind** [comment]
i forked then changed fofa api domain and build release version with github action ,
but search results with nothing :lady_beetle:  ...

**Comment by diauweb** [comment]
> i forked then changed fofa api domain and build release version with github action ,
> but search results with nothing :lady_beetle:  ...

please open a new issue and fill all the issue template items correctly to provide us more infomation, which can help us locate the bug you described better
