### ISSUE TITLE
fofa.so失效，要添加新的接口了

### ISSUE THREAD

**Issue by githack2016** [wgpsec/fofa_viewer#68]
**描述你遇到的问题**
清晰、准确地描述你遇到了什么问题。

**复现步骤**
出现问题前进行的操作：
1. 使用...功能
2. 输入了...
3. 出现了...问题

**预期行为**
描述你预期的正确行为

**屏幕截图**
最好提供出现问题时的截图。

**运行环境**
 - 操作系统 (例. Windows 10 21H1)
 - Java 版本 (`java -version`) (例. `java version "17.0.1" 2021-10-19 LTS`)
 - 软件版本 (例. 1.1.4_JDK8)

**补充说明**
其他相关内容，如配置文件和Stacktrace

**Comment by f1ashine** [comment]
已修改，请使用1.1.5版本
