### ISSUE TITLE
数据展现的一些问题

### ISSUE THREAD

**Issue by lonesomexz** [wgpsec/fofa_viewer#73]
查询的数据 和导出的数据顺序不一起 ，这样的话 如果人为按日期筛选无法筛选

**Comment by keac** [comment]
能够贴图描述一下吗，并且说明你期望的样子

**Comment by lonesomexz** [comment]
一个是查询时候的图片是顺序一致的,但是导出时候顺序全乱了 
![查询](https://user-images.githubusercontent.com/54177993/155128763-ab3596fe-4691-4b7e-b4f5-d36c565d5e7d.png)
![导出](https://user-images.githubusercontent.com/54177993/155128776-597e9f1c-ee87-4a8f-b7b7-b52ffc242f9a.png)
