### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Tukali** [wgpsec/fofa_viewer#74]
M1 Mac ,java11, 双击运行jar包无法运行，使用java -jar成功运行，但是报错

"TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit"

<img width="855" alt="CleanShot 2022-02-14 at 18 02 39@2x" src="https://user-images.githubusercontent.com/45891208/153842794-c0ba1965-3f6b-4096-ac37-9889c6d80b19.png">

**Comment by keac** [comment]
看起来像是网络问题，检查下是否能正常打开fofa

**Comment by Tukali** [comment]
> 

谢谢师傅，是开了代理的原因，关了就能打开了

**Comment by keac** [comment]
问题解决
