### ISSUE TITLE
[BUG]Mac在返回结果为1W条的情况下会软件崩溃和系统黑屏重启

### ISSUE THREAD

**Issue by zuiss** [wgpsec/fofa_viewer#78]
**描述你遇到的问题**
Mac在返回结果为1W条的情况下会软件崩溃和系统黑屏重启

**复现步骤**
出现问题前进行的操作：
1. title="test"

**预期行为**
描述你预期的正确行为

**屏幕截图**
最好提供出现问题时的截图。

**运行环境**
 - 操作系统 monterey 12.2.1
 - Java 版本 java version "11.0.14" 2022-01-18 LTS
 - 软件版本 FofaViewer_1.1.5-fixed

**补充说明**
其他相关内容，如配置文件和Stacktrace

**Comment by zuiss** [comment]
> 请问在软件出现问题时候内存占用率是多少

好像是70%多，我也不知道为啥，之前bigsur➕旧版本的fofaviewer就没这个问题。一打开cpu和内存就突然暴涨。

**Comment by keac** [comment]
看下来应该是系统的bug，团队师傅也出现升级系统大部分软件打不开的问题
