### ISSUE TITLE
[FEAT]请问Mac能用吗？

### ISSUE THREAD

**Issue by Mulburryrelic63** [wgpsec/fofa_viewer#79]
**我遇到了什么问题让我希望添加这项功能**
清晰地描述你遇到的问题和功能的使用场景

**你希望的解决方案**
准确清晰地告诉我们如何加入功能来满足你的需求

**另外的备选方案**
描述你认为也可以接受的备选方案

**其他内容**
放一些截图和其他有助于理解我们你的需求的内容

**Comment by keac** [comment]
请，仔细阅读readme后提issue，Mac可以用 谢谢
