### ISSUE TITLE
[BUG] use after and before with error

### ISSUE THREAD

**Issue by signfind** [wgpsec/fofa_viewer#82]
**描述你遇到的问题**

when i use after and befor at the same time,the soft notice me that 'it is not allowed to query before and after keywords at the same time' 
**复现步骤**

query keyword: `body="test" && after="2022-01-01" && before="2022-02-01"` 
but the same query work well at web browser,the query url : `https://fofa.info/result?qbase64=Ym9keT0idGVzdCIgJiYgYWZ0ZXI9IjIwMjItMDEtMDEiICYmIGJlZm9yZT0iMjAyMi0wMi0wMSI%3D`

maybe it's the limite of fofa ?
**预期行为**

**屏幕截图**

**运行环境**
 - 操作系统 
   
 - Java 版本 
   
 - 软件版本 
   

**补充说明**

**Comment by Laskeko** [comment]
Yes, that is fofa's limit. Api can not use "after" and "before" in the same time.

**Comment by signfind** [comment]
> Yes, that is fofa's limit. Api can not use "after" and "before" in the same time.

OK Thank u
