### ISSUE TITLE
Java17下 导出失败

### ISSUE THREAD

**Issue by BypassKing** [wgpsec/fofa_viewer#84]
Java17下 导出失败

![image](https://user-images.githubusercontent.com/98077736/156893376-81aea489-13db-494a-8e8e-2dec9813d12a.png)

![image](https://user-images.githubusercontent.com/98077736/156893421-1b105893-7ed2-45f4-a9e8-505fd21607a0.png)

**Comment by keac** [comment]
请参考 https://github.com/wgpsec/fofa_viewer/issues/50 内容进行尝试
