### ISSUE TITLE
[BUG] 选中标题查询无显示

### ISSUE THREAD

**Issue by coopliu** [wgpsec/fofa_viewer#91]
选中标题时查询无内容，去掉标题又有了

<img width="1149" alt="1" src="https://user-images.githubusercontent.com/55048424/163388230-143792ad-c6f4-456b-beb1-0a2644ab55d7.png">
<img width="1135" alt="2" src="https://user-images.githubusercontent.com/55048424/163388242-8a9b5e66-2f76-41e9-ae1f-3c876e5ba171.png">

**Comment by f1ashine** [comment]
参考 [README Q&A](https://github.com/wgpsec/fofa_viewer#qa) 第5条
