### ISSUE TITLE
为什么一直显示是查询状态，没有结果

### ISSUE THREAD

**Issue by wlxd001** [wgpsec/fofa_viewer#92]
初次安装，无法显示查询结果
![1652002404(1)](https://user-images.githubusercontent.com/38370225/167290405-cf2eed85-f23f-4a5b-9a3f-d8fcb6b90f28.jpg)

**Comment by keac** [comment]
请 java -jar 运行后贴上运行报错信息

**Comment by f1ashine** [comment]
试试1.1.8 版本呢
