### ISSUE TITLE
[BUG] 一个不知道是bug还是我操作失误

### ISSUE THREAD

**Issue by jiecoke** [wgpsec/fofa_viewer#93]
我查询的数据
![image](https://user-images.githubusercontent.com/39594997/167436850-0a52eebf-24a5-4c72-850f-343f31331aea.png)

我导出当前数据，打开表格显示只有这个
![image](https://user-images.githubusercontent.com/39594997/167436932-23dd35f2-f2be-48d2-8c41-3aa45dece3ec.png)

**Comment by keac** [comment]
看下面选择不同工作表

**Comment by jiecoke** [comment]
哦哦 不好意思，太粗心了

**Comment by jiecoke** [comment]
哦哦 不好意思，太粗心了
