### ISSUE TITLE
[BUG]反查证书失败 

### ISSUE THREAD

**Issue by Explore-c** [wgpsec/fofa_viewer#94]
系统：windows10
jdk：jdk1.8
工具版本：最新的1.8版本

如图，https网站没法反查，试了几个，都失败了
![image](https://user-images.githubusercontent.com/46821530/167621190-2de22054-6a89-4aa2-be1e-01a1b733e006.png)

**Comment by f1ashine** [comment]
新版更新会说明这个问题
