### ISSUE TITLE
[BUG] after和before语句一起查询就会报错

### ISSUE THREAD

**Issue by ZyRooting** [wgpsec/fofa_viewer#95]
![)X$KR}64XG}1Z K3~NKQYQT](https://user-images.githubusercontent.com/58015228/168317647-ddc070e2-9a5e-485e-9b16-20737dbceb6c.png)

**Comment by f1ashine** [comment]
非bug，官方有说明，具体请查阅https://shimo.im/docs/VrGRdTkrVvY3DQCj/read 
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/26664765/168439445-0a266c6d-93d8-4b49-a3bd-a1f7bfad239c.png">
