### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by gusechuisheng** [wgpsec/fofa_viewer#99]
win11,jdk8
![image](https://user-images.githubusercontent.com/49669724/175768572-2b26fc49-e61c-415c-8889-6b1d18657f1d.png)
直接懵了

**Comment by f1ashine** [comment]
![image](https://user-images.githubusercontent.com/26664765/175801341-644f8a13-52fe-4f29-bba5-8a5c8fd5dbee.png)
